### ISSUE TITLE
[Rust] Cannot package tool such as xplr

### ISSUE THREAD

**Issue by jaudiger** [brioche-dev/brioche-packages#39]
Due to relying on cargo install --frozen command to build and install the Rust package, I'm facing this issue:

```log
[86889]   Installing xplr v0.21.9 (/home/brioche-runner-833cd0961fae2b75be0c672a81727862ad6114bb1f393de6466
76a00fc40f7ce/work)
[86889]     Updating crates.io index
[86889] error: failed to get `ansi-to-tui` as a dependency of package `xplr v0.21.9 (/home/brioche-runner-8
33cd0961fae2b75be0c672a81727862ad6114bb1f393de646676a00fc40f7ce/work)`
[86889]
[86889] Caused by:
[86889]   attempting to make an HTTP request, but --frozen was specified
```

Surprisingly, this package tries to download a dependency through an HTTP request. Where the frozen clearly prevents this operation to be executed since it implies: --locked and --offline

**Comment by jaudiger** [comment]
I wonder if we should just call `cargo install --locked`.

**Comment by kylewlacy** [comment]
Okay, I think I figured out the issue after spotting this warning during the build:

> warning: both `/home/brioche-runner-833cd0961fae2b75be0c672a81727862ad114bb1f393de646676a00fc40f7ce/work/.cargo/config` and `/home/brioche-runner-833d0961fae2b75be0c672a81727862ad6114bb1f393de646676a00fc40f7ce/work/.cargo/config.toml` exist. Using `/home/brioche-runner-833cd0961fae2b75be0c672a81727862ad6114b1f393de646676a00fc40f7ce/work/.cargo/config`

Basically, it looks like `xplr` contains the file `.cargo/config` instead of `.cargo/config.toml`, then `cargo vendor` writes a new `.cargo/config.toml` file. When a crate contains both files, Cargo prefers `.cargo/config`, meaning `cargo vendor`'s output doesn't get used

The fix is basically to make sure we consolidate down to one file before the `cargo install` command, I'll open a PR with a fix shortly

**Comment by jaudiger** [comment]
Awesome! I'll give it a try!
